// 데모 모드 샘플 (API 키 없이 UI 확인용) — 스캔할 때마다 순환
export const DEMOS = [
  {
    found: true, confidence: 92, knowledge: "rich",
    basis: "세계적으로 널리 알려진 보르도 그랑 크뤼로 학습 지식이 풍부합니다.",
    category: "wine", name: "Château Margaux 2015", producer: "Château Margaux",
    type: "레드 와인 · 보르도 블렌드", vintage: "2015", region: "마고, 보르도", country: "프랑스", alcohol: "13.5%",
    liquidColor: "#5e1224",
    priceRange: "120~180만원", priceNote: "그레이트 빈티지로 프리미엄 형성", priceTier: 5,
    tasteProfile: [
      { axis: "바디", value: 88 }, { axis: "탄닌", value: 82 },
      { axis: "산도", value: 70 }, { axis: "당도", value: 12 },
    ],
    tastingNotes: "블랙커런트와 제비꽃, 삼나무 향이 겹겹이 피어납니다. 실크처럼 매끄러운 탄닌과 긴 여운이 인상적입니다.",
    specs: [
      { label: "품종", value: "카베르네 소비뇽 87%" }, { label: "숙성", value: "새 오크 100%, 18~24개월" },
      { label: "등급", value: "1855 그랑 크뤼 1등급" },
    ],
    ibu: null, srm: null, drinkFrom: "2025", drinkPeak: "2035", drinkUntil: "2055",
    history: [
      { year: "12세기", event: "마고 영지에 포도밭 조성 시작" },
      { year: "1855", event: "파리 만국박람회 등급 분류에서 1등급 지정" },
      { year: "1977", event: "멘체로풀로스 가문 인수 후 대대적 품질 개혁" },
      { year: "2015", event: "파비용 신축과 함께 세기의 빈티지 탄생" },
    ],
    story: "샤토 마고는 '와인의 여왕'이라 불리는 보르도 1등급 샤토입니다. 2015 빈티지는 완벽한 작황과 신축 셀러가 맞물린 상징적 해로 평가받습니다.",
    winery: "메독 마고 마을에 위치한 1855년 1등급 샤토. 우아함과 향의 복합미로 정평이 나 있습니다.",
    foodPairing: [
      { emoji: "🥩", food: "샤토브리앙 스테이크", why: "탄닌이 지방을 부드럽게 감쌉니다" },
      { emoji: "🍄", food: "트러플 리조또", why: "흙내음이 부케와 공명합니다" },
      { emoji: "🧀", food: "꽁떼 치즈", why: "견과류 풍미가 여운을 늘립니다" },
    ],
    pairingTip: "디캔팅 후 1~2시간 뒤가 최적입니다.", avoidPairing: "매운 음식은 탄닌을 거칠게 만듭니다.",
    ratings: [{ source: "Robert Parker", score: "100" }, { source: "James Suckling", score: "99" }],
    similar: ["Château Latour", "Château Haut-Brion"],
    trivia: "2015년은 샤토 마고 소유주 폴 폰탈리에의 마지막 빈티지로, 라벨에 그의 헌정 문구가 새겨졌습니다.",
    servingTemp: "16~18℃", servingNote: "보르도 글라스, 최소 1시간 디캔팅", aging: "새 프렌치 오크 18~24개월",
    tips: ["큰 볼의 글라스로 향을 모아보세요", "장기 보관 시 13℃ 셀러 보관이 이상적입니다"],
  },
  {
    found: true, confidence: 95, knowledge: "rich",
    basis: "아일라 대표 싱글몰트로 정보가 풍부합니다.",
    category: "whisky", name: "Lagavulin 16 Year Old", producer: "Lagavulin Distillery",
    type: "싱글몰트 스카치", vintage: null, region: "아일라", country: "스코틀랜드", alcohol: "43%",
    liquidColor: "#b8722c",
    priceRange: "13~17만원", priceNote: "면세·할인 시 11만원대", priceTier: 3,
    tasteProfile: [
      { axis: "바디", value: 80 }, { axis: "피트", value: 90 },
      { axis: "과일향", value: 45 }, { axis: "스파이스", value: 55 },
    ],
    tastingNotes: "짙은 피트 스모크와 요오드, 그 뒤로 셰리의 단맛과 말린 과일이 따라옵니다. 길고 따뜻한 피니시.",
    specs: [
      { label: "숙성", value: "16년, 유러피언 오크" }, { label: "캐스크", value: "버번 + 셰리" },
      { label: "냉각여과", value: "적용" },
    ],
    ibu: null, srm: null, drinkFrom: null, drinkPeak: null, drinkUntil: null,
    history: [
      { year: "1816", event: "존 존스턴이 아일라 남부 해안에 증류소 설립" },
      { year: "1988", event: "Classic Malts 6종에 선정되며 세계적 명성" },
      { year: "2016", event: "창립 200주년 기념 에디션 출시" },
    ],
    story: "라가불린 16년은 '아일라의 왕'으로 불리는 피트 위스키의 교과서입니다. 느린 증류와 긴 숙성이 만든 묵직한 스모크가 시그니처입니다.",
    winery: "아일라 섬 남쪽 해안의 증류소로, 이웃한 아드벡·라프로익과 함께 피트 3대장을 이룹니다.",
    foodPairing: [
      { emoji: "🦪", food: "생굴", why: "바다 내음과 스모크가 하나로 어우러집니다" },
      { emoji: "🧀", food: "블루치즈", why: "강한 풍미끼리 서로를 끌어올립니다" },
      { emoji: "🍫", food: "다크 초콜릿", why: "쌉쌀함이 피니시를 연장합니다" },
    ],
    pairingTip: "니트 또는 물 몇 방울로 향을 여세요.", avoidPairing: "섬세한 흰살 생선 요리",
    ratings: [{ source: "Whisky Bible", score: "95" }],
    similar: ["Ardbeg 10", "Laphroaig 10"],
    trivia: "드라마 '파크스 앤 레크리에이션'의 론 스완슨이 사랑한 위스키로 유명해져 미국 판매량이 급증했습니다.",
    servingTemp: "실온", servingNote: "튤립형 글렌캐런 글라스 권장", aging: "16년",
    tips: ["첫 모금 전 30초간 향을 먼저 즐기세요", "물 2~3방울이면 숨은 단맛이 열립니다"],
  },
  {
    found: true, confidence: 88, knowledge: "rich",
    basis: "일본 대표 프리미엄 사케로 정보가 충분합니다.",
    category: "sake", name: "獺祭 (닷사이) 순미대음양 23", producer: "旭酒造 (아사히주조)",
    type: "준마이 다이긴조", vintage: null, region: "야마구치현", country: "일본", alcohol: "16%",
    liquidColor: "#f4f0dc",
    priceRange: "9~13만원 (720ml)", priceNote: "정미율 23% 플래그십", priceTier: 4,
    tasteProfile: [
      { axis: "바디", value: 45 }, { axis: "감칠맛", value: 70 },
      { axis: "산도", value: 40 }, { axis: "당도", value: 35 },
    ],
    tastingNotes: "잘 익은 멜론과 배 향이 화사하게 피고, 입안에서는 비단결 같은 질감과 깨끗한 여운이 이어집니다.",
    specs: [
      { label: "정미보합", value: "23%" }, { label: "쌀 품종", value: "야마다니시키 100%" },
    ],
    ibu: null, srm: null, drinkFrom: null, drinkPeak: null, drinkUntil: null,
    history: [
      { year: "1948", event: "아사히주조 창업" },
      { year: "1990", event: "닷사이 브랜드 출시, 다이긴조 전문 전환" },
      { year: "2012", event: "정미율 23% '磨き二割三分' 세계적 히트" },
    ],
    story: "망해가던 시골 양조장이 '취하기 위한 술이 아닌 맛보기 위한 술'을 내걸고 다이긴조에 올인해 세계에서 가장 유명한 사케가 된 역전의 이야기입니다.",
    winery: "야마구치현 산골의 양조장으로, 토지(杜氏) 없이 데이터 기반 양조를 하는 것으로 유명합니다.",
    foodPairing: [
      { emoji: "🍣", food: "흰살 생선 사시미", why: "섬세한 향을 해치지 않습니다" },
      { emoji: "🦐", food: "새우 텐푸라", why: "기름기를 산뜻하게 씻어냅니다" },
      { emoji: "🧀", food: "부라타 치즈", why: "크리미함과 쌀의 단맛이 어울립니다" },
    ],
    pairingTip: "화이트와인 글라스에 차게 즐겨보세요.", avoidPairing: "향이 강한 붉은 육류 요리",
    ratings: [],
    similar: ["久保田 萬寿", "十四代 本丸"],
    trivia: "쌀알을 77%나 깎아내는 데 7일 밤낮이 걸립니다. 오바마 전 대통령 방일 만찬주로도 쓰였습니다.",
    servingTemp: "8~12℃", servingNote: "와인 글라스 사용 시 향이 배가됩니다", aging: null,
    tips: ["개봉 후 냉장 보관, 1주일 내 음용 권장", "온도가 오르며 변하는 향을 비교해보세요"],
  },
  {
    found: true, confidence: 97, knowledge: "rich",
    basis: "국내 대표 소주 제품으로 정보가 확실합니다.",
    category: "soju", name: "참이슬 후레쉬", producer: "하이트진로",
    type: "희석식 소주", vintage: null, region: "전국", country: "대한민국", alcohol: "16%",
    liquidColor: "#eef4f2",
    priceRange: "1,500~2,000원 (마트 기준)", priceNote: "음식점 5,000~6,000원", priceTier: 1,
    tasteProfile: [
      { axis: "바디", value: 25 }, { axis: "깔끔함", value: 85 },
      { axis: "곡물향", value: 30 }, { axis: "당도", value: 20 },
    ],
    tastingNotes: "대나무 숯 정제 특유의 깔끔하고 부드러운 목넘김. 은은한 단맛이 스치고 잡미 없이 떨어집니다.",
    specs: [
      { label: "정제", value: "대나무활성숯 4단 정제" }, { label: "감미", value: "과당·에리스리톨" },
    ],
    ibu: null, srm: null, drinkFrom: null, drinkPeak: null, drinkUntil: null,
    history: [
      { year: "1924", event: "진로 창립 (원숭이 상표 시대)" },
      { year: "1998", event: "'참이슬' 출시, 소주 도수 23도 시대 개막" },
      { year: "2006", event: "참이슬 후레쉬 출시" },
    ],
    story: "1998년 출시 이후 대한민국에서 가장 많이 팔린 소주. '이슬처럼 깨끗하게'라는 콘셉트로 소주의 저도수화 흐름을 이끌었습니다.",
    winery: "하이트진로는 세계 증류주 판매량 1위를 다투는 국내 최대 주류 기업입니다.",
    foodPairing: [
      { emoji: "🥓", food: "삼겹살", why: "기름기를 깔끔하게 정리해줍니다" },
      { emoji: "🐙", food: "낙지볶음", why: "매운맛을 부드럽게 받쳐줍니다" },
      { emoji: "🍲", food: "김치찌개", why: "국물의 감칠맛과 최고의 궁합" },
    ],
    pairingTip: "차갑게(5℃ 이하) 마실수록 깔끔합니다.", avoidPairing: "디저트류와는 어울리지 않습니다",
    ratings: [],
    similar: ["처음처럼", "진로이즈백"],
    trivia: "참이슬은 초당 약 53병씩 팔리는 것으로 알려져 있으며, 세계에서 가장 많이 팔리는 증류주 브랜드 중 하나입니다.",
    servingTemp: "4~6℃", servingNote: "잔은 소주잔, 첫 잔은 가득", aging: null,
    tips: ["냉동실에 살짝 얼려 슬러시로도 즐깁니다", "탄산수와 1:1로 섞으면 하이볼 스타일"],
  },
];
